### ISSUE TITLE
window.devicePixelRatio maybe a float value

### ISSUE THREAD

**Issue by zhangjialiang2007** [JordanDelcros/stats-js#5]
in the stats.js, we define PIXEL_RATIO as window.devicePixelRatio || 1;
but window.devicePixelRatio maybe a float value,and then the FRAMES.WIDTH will be float；
so we call new Array(SIZE.FRAMES.WIDTH),the application crash

so i suggest that we can use var PIXEL_RATIO = Math.round(window.devicePixelRatio || 1) instead

**Comment by JordanDelcros** [comment]
Trust you, done! 👍
